//===- ShaderTypes.td - Shader dialect types ---------------*- tablegen -*-===//
//
// This source file is part of the Shader open source project
// See LICENSE.txt for license information
//
//===----------------------------------------------------------------------===//

#ifndef SHADER_TYPES
#define SHADER_TYPES

include "mlir/IR/AttrTypeBase.td"
include "shader/IR/ShaderDialect.td"


#endif // SHADER_TYPES
